USE DataWarehouseAnalytics;


-- 1. Database Exploration 

-- Explore all objects in the Database

SELECT * FROM INFORMATION_SCHEMA.TABLES;


-- Explore all columns in the Database

SELECT * FROM INFORMATION_SCHEMA.COLUMNS

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';



-- 2. Dimensions Exploration

-- Explore all Countries our customers come from.

SELECT DISTINCT Country FROM Gold.dim_customers;

-- Explore all Categories "The Major Divisions"

SELECT DISTINCT Category FROM Gold.dim_products;


SELECT DISTINCT 
	Category, 
	Sub_Category, 
	Product_Name 
FROM Gold.dim_products
ORDER BY 1,2,3;



-- 3. Date Exploration

-- Find the date of the first and last order.
-- How Many Years of sales are Available.
-- How Many Months of Sales are available.

SELECT 
	MIN(Order_Date) AS First_Order_Date,
	MAX(Order_Date) AS Last_Order_Date,
	DATEDIFF(YEAR, MIN(Order_Date), MAX(Order_Date)) AS Order_Range_Years,
	DATEDIFF(MONTH, MIN(Order_Date), MAX(Order_Date)) AS Order_Range_Months
FROM Gold.fact_sales;


-- Find the Youngest and the oldest customer

SELECT 
	MIN(Birth_Date) AS Oldest_Birth_Date,
	DATEDIFF(YEAR, MIN(Birth_Date), GETDATE()) AS Oldest_Age,
	MAX(Birth_Date) AS Youngest_Birth_Date,
	DATEDIFF(YEAR, MAX(Birth_Date), GETDATE()) AS Youngest_Age
FROM Gold.dim_customers;



-- 4. Measures Exploration (Big Numbers)

-- Find the Total Sales

SELECT SUM(Sales_Amount) AS Total_Sales From Gold.fact_sales;

-- Find the how many items are sold

SELECT SUM(Sales_Quantity) AS Total_Quantity FROM Gold.fact_sales;

-- Find the Average selling price

SELECT AVG(Sales_Price) AS Avg_Sales_Price FROM Gold.fact_sales;

-- Find the toatl number of Orders

SELECT COUNT(Order_Number) AS Total_Orders FROM Gold.fact_sales;

SELECT COUNT(DISTINCT Order_Number) AS Total_Orders FROM Gold.fact_sales;

-- Find the toatl number of Products

SELECT COUNT(Product_Key) AS Total_Products FROM Gold.dim_products;

SELECT COUNT(DISTINCT Product_Key) AS Total_Products FROM Gold.dim_products;

-- Find the toatl number of Customers

SELECT COUNT(Customer_ID) AS Total_Customers FROM gold.dim_customers;

SELECT COUNT(DISTINCT Customer_ID) AS Total_Customers FROM gold.dim_customers;

-- Find the toatl number of Customers that has placed an order

SELECT COUNT(DISTINCT Customer_Key) AS Total_Customers FROM Gold.fact_sales;


-- Generate a report that shows all key metrics of the business

SELECT 'Total Sales' AS Measure_Name, SUM(Sales_Amount) AS Measure_Value From Gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS Measure_Name, SUM(Sales_Quantity) AS Measure_Value From Gold.fact_sales
UNION ALL
SELECT 'Average Sales Price' AS Measure_Name, AVG(Sales_Price) AS Measure_Value From Gold.fact_sales
UNION ALL
SELECT 'Nr of Orders' AS Measure_Name, COUNT(DISTINCT Order_Number) AS Measure_Value From Gold.fact_sales
UNION ALL
SELECT 'Nr of Products' AS Measure_Name, COUNT(DISTINCT Product_Key) AS Measure_Value From Gold.dim_products
UNION ALL
SELECT 'Nr of Customers' AS Measure_Name, COUNT(DISTINCT Customer_ID) AS Measure_Value From Gold.dim_customers




-- 5. Magnitude Analysis

-- Find total customers by countries

SELECT 
	Country,
	COUNT(Customer_ID) As Total_Customers
FROM Gold.dim_customers
GROUP BY Country
ORDER BY Total_Customers DESC;

-- Find total customers by gender

SELECT 
	Gender,
	COUNT(Customer_ID) AS Total_Customers
FROM Gold.dim_customers
GROUP BY Gender
ORDER BY Total_Customers DESC;

-- Find total Products by Category

SELECT 
	Category,
	COUNT(Product_Key) AS Total_Products
FROM Gold.dim_products
GROUP BY Category
ORDER BY Total_Products DESC;

-- What is the Average cost in each category?

SELECT
	Category,
	AVG(Product_cost) AS Avg_Product_Cost
FROM Gold.dim_products
GROUP BY Category
ORDER BY Avg_Product_Cost Desc;

-- What is the total Revenue generated for each	category?

SELECT 
	p.Category,
	SUM(Sales_Amount) AS Total_Revenue
FROM Gold.fact_sales AS f
LEFT JOIN Gold.dim_products AS p
ON f.Product_Key = p.Product_Key
GROUP BY p.Category
ORDER BY Total_Revenue DESC;

-- Find total revenue is generated by each customer

SELECT 
	c.Customer_Key,
	c.First_Name,
	c.Last_Name,
	SUM(f.Sales_Amount) AS Total_Revenue
FROM Gold.fact_sales AS f
LEFT JOIN Gold.dim_customers AS c
ON f.Customer_Key = c.Customer_Key
GROUP BY c.Customer_Key,
		 c.First_Name,
		 c.Last_Name
ORDER BY Total_Revenue DESC;

-- What is the distribution of sold items across countries?

SELECT 
	c.Country,
	SUM(f.Sales_Quantity) AS Total_Sold_Quantity
FROM Gold.fact_sales AS f
LEFT JOIN Gold.dim_customers AS c
ON f.Customer_Key = c.Customer_Key
GROUP BY c.Country
ORDER BY Total_Sold_Quantity DESC;




-- 6. Ranking Analysis

-- Which 5 products generate the highest revenue?

SELECT TOP 5
	p.Product_Name,
	SUM(Sales_Amount) AS Total_Revenue
FROM Gold.fact_sales AS f
LEFT JOIN Gold.dim_products AS p
ON f.Product_Key = p.Product_Key
GROUP BY p.Product_Name
ORDER BY Total_Revenue DESC;

SELECT *
FROM (
	SELECT
		p.Product_Name,
		SUM(Sales_Amount) AS Total_Revenue,
		ROW_NUMBER() OVER (ORDER BY SUM(Sales_Amount) DESC) AS Rank_Products
	FROM Gold.fact_sales AS f
	LEFT JOIN Gold.dim_products AS p
	ON f.Product_Key = p.Product_Key
	GROUP BY p.Product_Name) AS t
WHERE Rank_Products <= 5;

-- What are the 5 worst-Performing products in terms of sales?


SELECT TOP 5
	p.Product_Name,
	SUM(Sales_Amount) AS Total_Revenue
FROM Gold.fact_sales AS f
LEFT JOIN Gold.dim_products AS p
ON f.Product_Key = p.Product_Key
GROUP BY p.Product_Name
ORDER BY Total_Revenue ASC;


-- Top 3 customers with fewest orders placed

SELECT TOP 3
	c.Customer_Key,
	c.First_Name,
	c.Last_Name,
	COUNT(DISTINCT Order_Number) AS Total_Orders
FROM Gold.fact_sales AS f
LEFT JOIN Gold.dim_customers AS c
ON f.Customer_Key =c.Customer_Key
GROUP BY c.Customer_Key,
		 c.First_Name,
		 c.Last_Name
ORDER BY Total_Orders;

-- FInd the Top 10 customers who have generated the highest revenue

SELECT TOP 10
	c.Customer_Key,
	c.First_Name,
	c.Last_Name,
	SUM(f.Sales_Amount) AS Total_Revenue
FROM Gold.fact_sales AS f
LEFT JOIN Gold.dim_customers AS c
ON f.Customer_Key = c.Customer_Key
GROUP BY c.Customer_Key,
		 c.First_Name,
		 c.Last_Name
ORDER BY Total_Revenue DESC;